---

- set_fact:
    my_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
- local_action: copy content={{my_pass}} dest=/home/ubuntu/pass.txt
- debug:
    msg: "{{ my_pass }}"


